name: cron

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  import:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Import
        env:
          AAD_TENANT_ID: ${{ secrets.AAD_TENANT_ID }}
          AAD_CLIENT_ID: ${{ secrets.AAD_CLIENT_ID }}
          AAD_CLIENT_SECRET: ${{ secrets.AAD_CLIENT_SECRET }}
          RAGIC_URL: ${{ secrets.RAGIC_URL }}
          RAGIC_KEY: ${{ secrets.RAGIC_KEY }}
        run: |
          npm install
          npm start
